name: Add Approved Label (Reusable)

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node for Octokit
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Octokit
      run: npm install @octokit/rest

    - name: Add label
      run: |
        node -e "
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          (async () => {
            try {
              await octokit.rest.issues.addLabels({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.event.repository.name }}',
                issue_number: ${{ inputs.pr_number }},
                labels: ['Approved']
              });
              console.log('Label added successfully');
            } catch (error) {
              console.error('Failed to add label:', error.message);
              process.exit(1);
            }
          })();
        "
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
